M48
; DRILL file {KiCad 8.0.4} date 2024-07-28T20:23:24+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-28T20:23:24+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X2.2514Y-1.5299
X2.4423Y-1.5299
T2
X2.2396Y-1.4106
X2.4541Y-1.4106
M30
