M48
; DRILL file {KiCad 8.0.4} date 2024-08-18T14:41:27+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-18T14:41:27+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X5.8293Y-1.6843
X6.0203Y-1.6843
T2
X5.8175Y-1.565
X6.0321Y-1.565
M30
